#!/bin/bash -u
# this script will create "snapshot" backups, with common files hardlinked between

SOURCE="/"
DEST="/media/backup"
CURRENT="/media/backup/current"
TIMESTAMP=`date "+%Y-%m-%d+%H:%M:%S"`

CMD="rsync -aP --one-file-system"

mkdir "$DEST/incomplete" 2> /dev/null
mkdir "$DEST/snapshots" 2> /dev/null

if [ -d "$DEST/current" ]; then
	$CMD --link-dest="$DEST/" "$SOURCE" "$DEST/incomplete/$TIMESTAMP/"
else
	$CMD "$SOURCE" "$DEST/incomplete/$TIMESTAMP/"
fi

if [ -d "$DEST/incomplete/$TIMESTAMP" ]; then
	mv "$DEST/incomplete/$TIMESTAMP" "$DEST/snapshots/$TIMESTAMP"
	rm -f "$DEST/current"
	ln -s "snapshots/$TIMESTAMP" "$DEST/current"
	rmdir "$DEST/incomplete" 2> /dev/null
fi
