#!/bin/bash -u
CHROOT=/nfsroot/maverick

if [ "$(id -u)" != "0" ]; then
   echo \"chuseradd [user]\" must be run as root
   exit 1
fi

echo Adding user $1 locally...
useradd -mU -s /bin/bash $1
chown $1:$1 /home/$1
cd /home/$1

echo Regenerating SSH key...
sudo -u $1 mkdir .ssh 2>/dev/null
rm -f .ssh/id_rsa .ssh/id_rsa.pub
sudo -u $1 ssh-keygen -q -trsa -N "" -f .ssh/id_rsa

echo Adding user $1 inside chroot...
chroot $CHROOT useradd -mU -s /bin/bash $1
chroot $CHROOT chown $1:$1 /home/$1
mkdir $CHROOT/home/$1/.ssh 2>/dev/null

echo Installing SSH key...
cp /home/$1/.ssh/id_rsa $CHROOT/home/$1/.ssh/
cp /home/$1/.ssh/id_rsa.pub $CHROOT/home/$1/.ssh/
cp /home/$1/.ssh/id_rsa.pub $CHROOT/home/$1/.ssh/authorized_keys
chroot $CHROOT chown -R $1:$1 /home/$1/.ssh
chroot $CHROOT chmod 400 /home/$1/.ssh/id_rsa
