#!/usr/bin/python
import socket, time

global s
s = None
def connect():
        global s
        while True:
                try:
                        s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
                        s.connect(('mini', 8000))
                        break
                except socket.error:
                        time.sleep(0.5)

connect()
while True:
        try:
                s.send('\n')
        except socket.error:
                connect()

        time.sleep(0.5)

