#!/usr/bin/python
import socket, sys
s = socket.socket()
s.connect(('mini', 22))
addr = s.getsockname()[0]
s.close()
f = open('/etc/hosts', 'r')
for line in f.read().split('\n'):
	if line.endswith('#Cluster Node'):
		ip, host = line.split(' ',2)[:2]
		if ip == addr:
			print host
			sys.exit(0)

sys.exit(1)
